version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - .logs/apache2:/var/log/apache2